baseURL = ""
languageCode = "en-us"
theme = "projects-theme"
title = "epinio"
pluralizeListTitles = false
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableGitInfo = true

[blackfriday]
fractions = false
#hrefTargetBlank = true

[outputFormats.Algolia]
baseName = "algolia"
isPlaintext = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]

[params]
# rename when the logo is updated, so we indirectly also invalidate caches
logo = "images/epinio-logo-header.png"
githubLink = "https://github.com/epinio/epinio"
docsLink = "https://docs.epinio.io/"
css = ["css/custom.css"]
favicon = "images/favicon.ico"
  github = "https://github.com/epinio/epinio"

[outputs]
  home = ["HTML", "RSS", "Algolia"]

[privacy]
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = true

[menu]

  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "https://github.com/epinio/epinio/docs/install.md"
    weight = -110
    