baseURL = "https://epinio.github.io/epinio.io/"
languageCode = "en-us"
theme = "portio-hugo"
title = "epinio"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

[[menu.main]]


[params]
# rename when the logo is updated, so we indirectly also invalidate caches
logo = "images/epinio-logo-header.png"
githubLink = "https://github.com/epinio/epinio"
docsLink = "https://docs.epinio.io/"
css = ["css/custom.css"]
favicon = "images/favicon.ico"
