[_]
schema-version="0.2"

[[io.buildpacks.group]]
uri="paketo-buildpacks/environment-variables"

[[io.buildpacks.build.env]]
name="BP_NODE_RUN_SCRIPTS"
value="build:nogit"

[[io.buildpacks.build.env]]
name="HUGO_ENABLEGITINFO"
value="false"

[[io.buildpacks.build.env]]
name="GIT_DISCOVERY_ACROSS_FILESYSTEM"
value="1"

[[build.env]]
name="BP_NODE_RUN_SCRIPTS"
value="build:nogit"

[[build.env]]
name="HUGO_ENABLEGITINFO"
value="false"

[[build.env]]
name="GIT_DISCOVERY_ACROSS_FILESYSTEM"
value="1"

[[io.buildpacks.run.env]]
BP_WEB_SERVER_ROOT='public'
BP_WEB_SERVER='nginx'
BPE_HUGO_ENABLEGITINFO='false'
BPE_GIT_DISCOVERY_ACROSS_FILESYSTEM='1'
