[_]
schema-version = "0.2"

[[io.buildpacks.build.env]]
name = "BP_NODE_RUN_SCRIPTS"
value = "build"

[[io.buildpacks.build.env]]
name = "HUGO_ENABLEGITINFO"
value = "false"

[[io.buildpacks.build.env]]
name = "GIT_DISCOVERY_ACROSS_FILESYSTEM"
value = "1"

[[io.buildpacks.run.env]]
BP_WEB_SERVER_ROOT='public'
BP_WEB_SERVER='nginx'
HUGO_ENABLEGITINFO='false'
GIT_DISCOVERY_ACROSS_FILESYSTEM='1'
