name: Publish Site
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true

        # We use a forked action due to
        # https://github.blog/2022-04-12-git-security-vulnerability-announced/ (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24765).
      - name: Publish Site
        uses: kubewarden/hugo-gh-pages@fix-publishing
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          hugoVersion: extended_0.82.0
