name: Test Site

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Upload visual diff artifacts if tests failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: visual-diff
          path: test/__image_snapshots__/__diff_output__/
          if-no-files-found: ignore
